### ISSUE TITLE
企画ミーティング

### ISSUE THREAD

**Issue by Kuya0307** [Kuya0307/BlockBreak#8]

**Comment by kuboi0627** [comment]
# 機能（できれば入れたい機能）
* 壊れないブロックの配置
* 取ると当てる球の複数生成するアイテム
* 時間制限を付ける
* ブロックを壊すとポイントゲット
* 時間内にすべて壊すとボーナスポイント
* 取ると動かすバーが長くなるアイテム
* 取ると動かすバーが短くなるアイテム
* 複数回当てないと壊れないブロックの配置

**Comment by Kuya0307** [comment]
# ブロック崩し
* ボールを動かしブロックを消していき、全部消すことができたらクリア。
* クリア時間をスコアにするまたはスコアプラスクリア時間。
* ボールが一回当たったら消えるブロック、二回当たったら消えるブロック、三回当たったら消えるブロックみたいに層ごと・ステージごとに難易度を付ける。
* クイズの問題文を背景画像にしてゲームオーバーまたはゲームクリアしたら回答する。(回答は選択式)
* ボールを反射させるバーの速度を調整して難易度を付ける。
* ボールの大きさを調整して難易度を付ける。
* 一定時間経過したらボールの個数を増やす。

**Comment by kaburiba** [comment]
#概要 タイトル Blockbreak

ジャンル ブロック崩し

プラットフォーム 動作環境: PC 開発環境: javaScriptフレームワーク phaser ターゲット 5歳以上のライト層

概要: タイトルは無し。いきなりゲームを開始する。

 背景は一枚絵。

スクロールしない ゲーム開始時の バー の初期位置は画面中央下

 バー は左右に動かせる 

バー と ボール 間に当たり判定あり 

バー と ボールは画面外に移動できない

 オブジェクトはバー と ボールの 3 種類 ボール は動きまわる 

ブロック は静止している

 ボールが画面下外にでたらゲームオーバー ボール がブロックに触れたらそのブロックを消す

 ぼーる がブロックを消したらゲームクリア 時間制限を設ける

 残り時間は画面中央に表示する



 クリア条件: ぼーる が全てのブロックを消す



 ゲームオーバー条件:
ボールが画面下外にでる
 制限時間切れ

**Comment by shimiharu** [comment]
- 複数回当てないと消えないブロック 
- お邪魔ブロック 
- 特定のブロックを消すとスピードアップ

**Comment by Kuya0307** [comment]
# ブロック崩し

## ジャンル ブロック崩し
### プラットフォーム 動作環境: PC 開発環境: javaScriptフレームワーク phaser ターゲット 5歳以上のライト層
- 概要: タイトルは無し。いきなりゲームを開始する。
- 背景は一枚絵。
- 壊れないブロックの配置
- 取ると当てる球の複数生成するアイテム
- 時間制限を付ける
- ブロックを壊すとポイントゲット
- 時間内にすべて壊すとボーナスポイント
- 取ると動かすバーが長くなるアイテム
- 取ると動かすバーが短くなるアイテム
- 複数回当てないと壊れないブロックの配置

- ボールを動かしブロックを消していき、全部消すことができたらクリア。
- クリア時間をスコアにするまたはスコアプラスクリア時間。
- ボールが一回当たったら消えるブロック、二回当たったら消えるブロック、三回当たったら消えるブロックみたいに層ごと・ステージごとに難易度を付ける。
- クイズの問題文を背景画像にしてゲームオーバーまたはゲームクリアしたら回答する。(回答は選択式)
- ボールを反射させるバーの速度を調整して難易度を付ける。
- ボールの大きさを調整して難易度を付ける。
- 一定時間経過したらボールの個数を増やす。
- 複数回当てないと消えないブロック
- お邪魔ブロック
- 特定のブロックを消すとスピードアップ

**Comment by Kuya0307** [comment]
プロジェクト作成完了したため、クローズする。
